language: java
jdk:
  - openjdk17

branches:
  only:
    - main

before_script:
  - cd porthub/

#before_install:
#  - chmod +x gradlew

# Travis CI 서버의 Homes
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r PortfolioHub *
  - mkdir -p deploy
  - mv PortfolioHub.zip deploy/PortfolioHub.zip

deploy:
  - provider: porthub-s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: porthub-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deploy: true
    on:
      all_branches: true
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - wjdgusdlekd3@yonsei.ac.kr
