language: java
jdk:
  - openjdk17

branches:
  only:
    - main

before_script:
  - cd porthub/

#before_install:
#  - chmod +x gradlew

# Travis CI 서버의 Homes
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - wjdgusdlekd3@yonsei.ac.kr
