language: java
jdk:
  - openjdk17

branches:
  only:
    - main

before_script:
  - cd porthub/

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Homes
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/PortfolioHub.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket: porthub-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deploy: true
    on:
      all_branches: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: porthub-s3
    key: PortfolioHub.zip
    bundle_type: zip
    application: PortfolioHub
    deployment_group: PortfolioHub-group
    region: ap-northeast-2
    wait-until-deploy: true
    on:
      all_branches: true
# CI 실행 완료시d 메일로 알람
notifications:
  email:
    recipients:
      - wjdgusdlekd3@yonsei.ac.kr
