server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-2.czqsyq4cefmv.ap-northeast-2.rds.amazonaws.com:3306/porthub?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: porthub24


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

