server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-2.czqsyq4cefmv.ap-northeast-2.rds.amazonaws.com:3306/porthub?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: porthub24

  mail:
    host: smtp.gmail.com
    port: 587
    username: wjdgusdlekd3@yonsei.ac.kr
    password: scmf alhv vzev uxdp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#            required: true
#          connectiontimeout: 5000
#          timeout: 5000
#          writetimeout: 5000
#    auth-code-expiration-millis: 300000


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
